http_server:
  livetour_address: 0.0.0.0:8081
  app_address: 0.0.0.0:8080

s3:
  host: http://minio:9000
  bucket: virtual-tour
  images_path: images/

db:
  host: postgres:5432
  ssl_mode: disable
  migrations_path: migrations/
